package fr.robie.craftengineconverter.common.permission;

public enum Permission {
    COMMAND_USE("Allows the user to use the main command of the plugin."),
    COMMAND_RELOAD("Allows the user to reload the plugin configuration."),
    COMMAND_CONVERT("Allows the user to convert assets for CraftEngine"),

    NEXO_BLOCK_INTERACT_CONVERSION("Allows the user to convert Nexo blocks on interaction"),
    NEXO_FURNITURE_INTERACT_CONVERSION("Allows the user to convert Nexo furniture on interaction"),

    ITEMSADDER_BLOCK_INTERACT_CONVERSION("Allows the user to convert ItemsAdder blocks on interaction"),
    ITEMSADDER_FURNITURE_INTERACT_CONVERSION("Allows the user to convert ItemsAdder furniture on interaction")
    ;
    private final String description;
    private final String[] args;

    Permission() {
        this.description = "";
        this.args = new String[0];
    }

    Permission(String description, String... args) {
        this.description = description;
        this.args = args;
    }

    /**
     * Generates the permission string for this enum constant.
     * Converts the enum constant name to lowercase and replaces underscores with periods.
     *
     * @return The permission string.
     */
    public String asPermission() {
        return "craftengineconverter."+name().toLowerCase().replace("_", ".");
    }

    public String toPermission() {
        StringBuilder builder = new StringBuilder(asPermission());
        for (int i = 0; i < this.args.length; i++) {
            builder.append("<");
            builder.append(this.args[i]);
            builder.append(">");
            if (i < this.args.length - 1) {
                builder.append(".");
            }
        }
        return builder.toString();
    }

    /**
     * Generates a permission string for this enum constant with an additional suffix.
     * Appends the specified suffix to the permission string generated by {@link #asPermission()}.
     *
     * @param with The suffix to append.
     * @return The permission string with the suffix.
     */
    public String asPermission(String with) {
        return asPermission() + with;
    }

    public String getDescription() {
        return description;
    }

    public String[] getArgs() {
        return args;
    }
}
